name: Complex
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
     -name: step 1
      -run: date
  windows:
    runs-on: windows-latest
    steps:
     -name: step 1
      -run: date
  macod:  
    runs-on: macos-latest
    steps:
     -name: step 1
      -run: date
  depends:  
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
     -name: step 1
      -run: date
